# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  JavaProjectAnalyzer_config = debug

else ifeq ($(config),release)
  JavaProjectAnalyzer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := JavaProjectAnalyzer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

JavaProjectAnalyzer:
ifneq (,$(JavaProjectAnalyzer_config))
	@echo "==== Building JavaProjectAnalyzer ($(JavaProjectAnalyzer_config)) ===="
	@${MAKE} --no-print-directory -C . -f JavaProjectAnalyzer.make config=$(JavaProjectAnalyzer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f JavaProjectAnalyzer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   JavaProjectAnalyzer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"